#!/bin/bash
# Auto-generated fix script for Google OAuth
# Generated by diagnose_oauth.py

echo "🔧 תיקון Google OAuth Configuration"
echo "====================================="
echo ""

# 1. Check .env.local
if [ ! -f .env.local ]; then
    echo "❌ .env.local לא קיים - יוצר מ-.env.local.example"
    cp .env.local.example .env.local
    echo "✅ נוצר .env.local"
    echo "⚠️  ערוך את הקובץ והוסף את הערכים מ-Supabase Dashboard"
    exit 1
fi

# 2. Validate environment variables
if ! grep -q "supabase.co" .env.local; then
    echo "❌ VITE_SUPABASE_URL לא מוגדר ב-.env.local"
    echo "הוסף: VITE_SUPABASE_URL=https://ohgjascuewpmgukajvjd.supabase.co"
fi

# 3. Build the project
echo "🔨 Building project..."
npm run build

if [ $? -eq 0 ]; then
    echo "✅ Build הצליח"
else
    echo "❌ Build נכשל - בדוק שגיאות"
    exit 1
fi

# 4. Instructions for Netlify
echo ""
echo "📝 צעדים ידניים נדרשים:"
echo "========================"
echo ""
echo "1️⃣  Supabase Dashboard:"
echo "   → https://supabase.com/dashboard/project/ohgjascuewpmgukajvjd/auth/providers"
echo "   → ודא ש-Google Provider מופעל"
echo ""
echo "2️⃣  Supabase Redirect URLs:"
echo "   → https://supabase.com/dashboard/project/ohgjascuewpmgukajvjd/auth/url-configuration"
echo "   → הוסף:"
echo "      • https://rachel.woretaw.net"
echo "      • https://rachel.woretaw.net/"
echo "      • http://localhost:5173"
echo ""
echo "3️⃣  Google Cloud Console:"
echo "   → https://console.cloud.google.com/apis/credentials"
echo "   → Authorized JavaScript origins:"
echo "      • https://ohgjascuewpmgukajvjd.supabase.co"
echo "   → Authorized redirect URIs:"
echo "      • https://ohgjascuewpmgukajvjd.supabase.co/auth/v1/callback"
echo ""
echo "4️⃣  Netlify Environment Variables:"
echo "   → https://app.netlify.com → Site settings → Environment variables"
echo "   → הוסף:"
echo "      • VITE_SUPABASE_URL = https://ohgjascuewpmgukajvjd.supabase.co"
echo "      • VITE_SUPABASE_ANON_KEY = (העתק מ-Supabase)"
echo ""
echo "5️⃣  Netlify Deploy:"
echo "   → Deploys → Trigger deploy → Clear cache and deploy site"
echo ""
echo "✅ סיימת את כל השלבים? נסה להתחבר שוב!"
